import "server-only";
import { eq } from "drizzle-orm";
import { db } from "./client";

/* Plain DB readers returning the SAME shapes the components used to import from
   src/data/*. Public pages are statically generated (queries run at build) and
   regenerated by `revalidatePath("/", "layout")` after any admin edit, so no
   per-request cache layer is needed. */

export async function getCatalog() {
  const rows = await db.query.categories.findMany({
    orderBy: (t, { asc }) => asc(t.order),
    with: { image: true, products: { orderBy: (t, { asc }) => asc(t.order) } },
  });
  return rows.map((c) => ({
    id: c.slug,
    title: c.title,
    blurb: c.blurb,
    image: c.image?.url ?? "",
    // Hide unpriced drafts (price 0) from the public site so "from ₹0" never shows.
    products: c.products.filter((p) => p.price > 0).map((p) => ({
      name: p.name,
      price: p.price,
      specs: p.specs,
      note: p.note ?? undefined,
      popular: p.popular || undefined,
    })),
  }));
}

export async function getCategories() {
  const rows = await db.query.categories.findMany({
    orderBy: (t, { asc }) => asc(t.order),
    with: {
      image: true,
      hero: true,
      products: { orderBy: (t, { asc }) => asc(t.order) },
      images: { orderBy: (t, { asc }) => asc(t.order), with: { media: true } },
      services: { orderBy: (t, { asc }) => asc(t.order) },
    },
  });
  return rows.map((c) => ({
    id: c.slug,
    slug: c.slug,
    title: c.title,
    blurb: c.blurb,
    image: c.image?.url ?? "",
    heroImage: c.hero?.url ?? c.image?.url ?? "",
    longDescription: c.longDescription,
    metaTitle: c.metaTitle ?? undefined,
    metaDescription: c.metaDescription ?? undefined,
    videoIds: c.videoIds,
    serviceSlugs: c.services.map((s) => s.serviceSlug),
    images: c.images.map((ci) => ci.media.url),
    products: c.products.filter((p) => p.price > 0).map((p) => ({
      name: p.name,
      price: p.price,
      specs: p.specs,
      note: p.note ?? undefined,
      popular: p.popular || undefined,
    })),
  }));
}

export async function getFullCategory(slug: string) {
  return (await getCategories()).find((c) => c.slug === slug);
}

export async function getCategoryNav() {
  const rows = await db.query.categories.findMany({ orderBy: (t, { asc }) => asc(t.order) });
  return rows.map((c) => ({
    label: c.title,
    short: c.shortLabel ?? c.title,
    href: `/category/${c.slug}`,
    slug: c.slug,
  }));
}

export async function getServices() {
  const rows = await db.query.services.findMany({
    orderBy: (t, { asc }) => asc(t.order),
    with: {
      hero: true,
      sections: { orderBy: (t, { asc }) => asc(t.order) },
      images: { orderBy: (t, { asc }) => asc(t.order), with: { media: true } },
    },
  });
  return rows.map((s) => ({
    slug: s.slug,
    title: s.title,
    eyebrow: s.eyebrow,
    summary: s.summary,
    heroImage: s.hero?.url ?? "",
    intro: s.intro,
    metaTitle: s.metaTitle ?? undefined,
    metaDescription: s.metaDescription ?? undefined,
    sections: s.sections.map((sec) => ({ heading: sec.heading, body: sec.body })),
    gallery: s.images.map((si) => si.media.url),
    relatedCategoryId: s.relatedCategorySlug,
  }));
}

export async function getService(slug: string) {
  return (await getServices()).find((s) => s.slug === slug);
}

export async function getGallery() {
  const rows = await db.query.galleryCategories.findMany({
    orderBy: (t, { asc }) => asc(t.order),
    with: { images: { orderBy: (t, { asc }) => asc(t.order), with: { media: true } } },
  });
  const galleryCategories = rows.map((g) => ({
    id: g.slug,
    label: g.label,
    images: g.images.map((gi) => gi.media.url),
  }));
  return { galleryCategories, allGalleryImages: galleryCategories.flatMap((g) => g.images) };
}

export async function getTestimonials() {
  const rows = await db.query.testimonials.findMany({ orderBy: (t, { asc }) => asc(t.order) });
  return rows.filter((t) => t.published).map((t) => ({ quote: t.quote, name: t.name, role: t.role }));
}

export async function getLocations() {
  const rows = await db.query.locations.findMany({
    orderBy: (t, { asc }) => asc(t.order),
    with: { image: true },
  });
  return rows.map((l) => ({ name: l.name, blurb: l.blurb, image: l.image?.url ?? "" }));
}

export async function getSite() {
  const row = await db.query.siteSettings.findFirst({ where: (t) => eq(t.id, 1) });
  return row!;
}

export async function getSlots(key: string) {
  const rows = await db.query.imageSlots.findMany({
    where: (t) => eq(t.key, key),
    orderBy: (t, { asc }) => asc(t.order),
    with: { media: true },
  });
  return rows.map((r) => ({
    url: r.media?.url ?? "",
    alt: r.media?.alt ?? "",
    label: r.label ?? undefined,
    href: r.href ?? undefined,
  }));
}

export async function getSlot(key: string) {
  return (await getSlots(key))[0]?.url ?? "";
}

export async function getBookingCatalog() {
  const cats = await db.query.categories.findMany({
    orderBy: (t, { asc }) => asc(t.order),
    with: { products: { with: { tiers: true, blackouts: true }, orderBy: (t, { asc }) => asc(t.order) } },
  });
  return cats.map((c) => ({
    slug: c.slug,
    title: c.title,
    products: c.products.map((p) => ({
      id: p.id,
      name: p.name,
      price: p.price,
      tiers: p.tiers
        .slice()
        .sort((a, b) => a.startOn.localeCompare(b.startOn))
        .map((t) => ({ label: t.label, startOn: t.startOn, endOn: t.endOn, price: t.price })),
      blackouts: p.blackouts.map((b) => b.day),
    })),
  }));
}

/** Days blocked for ALL packages (productId null). */
export async function getGlobalBlackoutDays(): Promise<string[]> {
  const rows = await db.query.blackoutDates.findMany();
  return rows.filter((r) => r.productId == null).map((r) => r.day);
}

export async function getLegalPages() {
  return db.query.legalPages.findMany({ orderBy: (t, { asc }) => asc(t.order) });
}

export async function getLegalPage(slug: string) {
  return db.query.legalPages.findFirst({ where: (t) => eq(t.slug, slug) });
}
