// AUTO-GENERATED by scripts/gen-gallery.mjs — do not edit by hand.
export interface GalleryCategory {
  id: string;
  label: string;
  images: string[];
}

export const galleryCategories: GalleryCategory[] = [
  {
    "id": "beach",
    "label": "Beach",
    "images": [
      "/img/beach/beach-photoshoot-at-havelock-andaman.webp",
      "/img/beach/best-beach-photoshoot-in-havelock.webp",
      "/img/beach/best-beach-side-photoshoot-in-havelock.webp",
      "/img/beach/candid-beach-shoot-andaman.webp",
      "/img/beach/couple-poses-for-photoshoot-in-andaman.webp",
      "/img/beach/friends-beach-shoot-at-havelock.webp",
      "/img/beach/honeymoon-couple-andaman-islands-shoot.webp",
      "/img/beach/honeymoon-couple-beach-photoshoot.webp",
      "/img/beach/infant-beach-photoshoot-at-havelock-island.webp",
      "/img/beach/photoshoot-at-radhanagar-beach.webp",
      "/img/beach/premium-photoshoot-in-havelock.webp"
    ]
  },
  {
    "id": "sunset",
    "label": "Sunset",
    "images": [
      "/img/sunset/best-andaman-photography-for-sunset.webp",
      "/img/sunset/best-sunset-couple-shoot-in-andaman.webp",
      "/img/sunset/best-sunset-photography-in-andaman-islands.webp",
      "/img/sunset/couple-sunset-photography-in-andaman.webp",
      "/img/sunset/couple-sunset-shoot-havelock-island.webp",
      "/img/sunset/family-sunset-photography-at-havelock-andaman.webp",
      "/img/sunset/havelock-island-radhanagar-beach-sunset-shoot.webp",
      "/img/sunset/perfect-sunset-shoots-at-havelock.webp",
      "/img/sunset/radhanagar-beach-candid-sunset-photoshoot.webp",
      "/img/sunset/sunset-photoshoot-havelock-island.webp"
    ]
  },
  {
    "id": "forest",
    "label": "Forest",
    "images": [
      "/img/forest/awesome-couple-photoshoots-in-havelockisland.webp",
      "/img/forest/best-forest-photoshoot-in-havelock-island.webp",
      "/img/forest/best-forest-shoot-at-havelock.webp",
      "/img/forest/best-shoot-for-couples-at-forest.webp",
      "/img/forest/couple-forest-photoshoot-in-andaman.webp",
      "/img/forest/couple-forest-shoot-near-radhanagar.webp",
      "/img/forest/couple-shoot-near-radhanagar-beach.webp",
      "/img/forest/family-photoshoot-at-forest-at-andaman.webp",
      "/img/forest/forest-photoshoot-in-andaman.webp",
      "/img/forest/honeymoon-couple-forest-shoot-andaman-islands.webp",
      "/img/forest/premium-shoot-at-havelock-island.webp"
    ]
  },
  {
    "id": "candid",
    "label": "Candid",
    "images": [
      "/img/candid/best-candid-photography-in-andaman.webp",
      "/img/candid/best-candid-photoshoot-in-andaman.webp",
      "/img/candid/candid-photography-in-andaman.webp",
      "/img/candid/couple-candid-shoot-in-andaman.webp",
      "/img/candid/family-candid-photoshoot-in-andaman.webp",
      "/img/candid/honeymoon-couple-candid-photography.webp",
      "/img/candid/moments-capture.webp",
      "/img/candid/moments-photoshoot-candid.webp",
      "/img/candid/premium-candid-shoot-in-havelock-island.webp"
    ]
  },
  {
    "id": "cld",
    "label": "Candle-Light",
    "images": [
      "/img/cld/best-cld-photoshoot-in-andaman.webp",
      "/img/cld/best-honeymoon-couple-cld-photoshoot.webp",
      "/img/cld/candle-light-dinner-photoshoot-at-havelock-island.webp",
      "/img/cld/candle-light-dinner-photoshoot-in-andaman.webp",
      "/img/cld/cld-beach-photoshoot-and-video.webp",
      "/img/cld/cld-photoshoot-havelock-island.webp",
      "/img/cld/couple-beach-cld-photoshoot.webp",
      "/img/cld/moments-from-beach-photoshoot-at-Havelock-island.webp",
      "/img/cld/professional-candle-light-dinner-shoot.webp"
    ]
  },
  {
    "id": "post-wedding",
    "label": "Pre / Post Wedding",
    "images": [
      "/img/post-wedding/best-photoshoot-for-post-wedding.webp",
      "/img/post-wedding/couple-post-wedding-andaman-shoot.webp",
      "/img/post-wedding/couple-pre-post-wedding-shoot-at-havelock.webp",
      "/img/post-wedding/honeymoon-couple-post-wedding-shoot.webp",
      "/img/post-wedding/post-wedding-shoot-at-havelock.webp",
      "/img/post-wedding/post-wedding-shoot-in-andaman.webp",
      "/img/post-wedding/pre-post-wedding-shoot-in-andaman-islands.webp",
      "/img/post-wedding/premium-post-wedding-shoots.webp",
      "/img/post-wedding/premium-quality-edits-with-post-wedding-shoot-in-andaman.webp"
    ]
  },
  {
    "id": "property",
    "label": "Property",
    "images": [
      "/img/property/5-star-property-shoot-in-andaman.webp",
      "/img/property/5-star-resorts-shoot-in-havelock-island.webp",
      "/img/property/best-photography-at-havelock.webp",
      "/img/property/couple-photography-at-havelock-island.webp",
      "/img/property/honeymoon-couple-propertyshoot-at-havelock-island.webp",
      "/img/property/personalised-photoshoot-for-couples.webp",
      "/img/property/property-shoot-at-havelock-andaman.webp",
      "/img/property/resort-photography-for-couples.webp"
    ]
  },
  {
    "id": "bday",
    "label": "Birthday",
    "images": [
      "/img/bday/best-birthday-shoot-in-andaman.webp",
      "/img/bday/birthday-shoot-andaman-for-couples.webp",
      "/img/bday/birthday-shoot-andaman-island-cost.webp",
      "/img/bday/birthday-shoot-andaman-island-packages.webp",
      "/img/bday/birthday-shoot-in-andaman-island.webp",
      "/img/bday/birthday-shoot-in-andaman.webp",
      "/img/bday/popular-birthday-party-photographers.webp",
      "/img/bday/popular-birthday-party-photoshoot.webp"
    ]
  }
];

export const allGalleryImages: string[] = galleryCategories.flatMap((c) => c.images);
